# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Median <- function(x) {
    .Call('_biggrExtra_Median', PACKAGE = 'biggrExtra', x)
}

Quantile <- function(x, probs) {
    .Call('_biggrExtra_Quantile', PACKAGE = 'biggrExtra', x, probs)
}

estMC <- function(mc, ci_fun, conf_level = 0.95, mu = 1) {
    .Call('_biggrExtra_estMC', PACKAGE = 'biggrExtra', mc, ci_fun, conf_level, mu)
}

perci <- function(theta, conf_level = 0.95) {
    .Call('_biggrExtra_perci', PACKAGE = 'biggrExtra', theta, conf_level)
}

bca <- function(theta, conf_level = 0.95) {
    .Call('_biggrExtra_bca', PACKAGE = 'biggrExtra', theta, conf_level)
}

concatenate <- function(x, y) {
    .Call('_biggrExtra_concatenate', PACKAGE = 'biggrExtra', x, y)
}

drawNorm <- function(mu, sd, n) {
    .Call('_biggrExtra_drawNorm', PACKAGE = 'biggrExtra', mu, sd, n)
}

vecDraws <- function(x, size, n_iter) {
    .Call('_biggrExtra_vecDraws', PACKAGE = 'biggrExtra', x, size, n_iter)
}

compareCounts <- function(draws, n_observed) {
    .Call('_biggrExtra_compareCounts', PACKAGE = 'biggrExtra', draws, n_observed)
}

simPval <- function(sim, mu = 1, median_estimate = FALSE) {
    .Call('_biggrExtra_simPval', PACKAGE = 'biggrExtra', sim, mu, median_estimate)
}

